apiVersion: v1
kind: Secret
metadata:
  name: nestjs-app-secrets
type: Opaque
data:
  DATABASE_URL: cG9zdGdyZXNxbDovL3Bvc3RncmVzOnBvc3RncmVzQGRlZmF1bHQuc3ZjLmNsdXN0ZXIubG9jYWw6NTQzMi9wb3N0Z3Jlcw==
  JWT_SECRET: and3dC1zZWNyZXQ=
  PASSWORD_SALT: U0FMVDEyMw==

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nestjs-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nestjs-app
  template:
    metadata:
      labels:
        app: nestjs-app
    spec:
      containers:
        - name: nestjs-app
          image: <tu_usuario_dockerhub>/<nombre_de_tu_imagen_nestjs>:production
          ports:
            - containerPort: 3000
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: nestjs-app-secrets
                  key: DATABASE_URL
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: nestjs-app-secrets
                  key: JWT_SECRET
            - name: PASSWORD_SALT
              valueFrom:
                secretKeyRef:
                  name: nestjs-app-secrets
                  key: PASSWORD_SALT

---
apiVersion: v1
kind: Service
metadata:
  name: nestjs-app-service
spec:
  selector:
    app: nestjs-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP
